#!/bin/bash

# 安装完成之后执行业务

sudo python3 -m pip install --upgrade --break-system-packages --root-user-action=ignore armcnc



if python3 -c "import pkgutil; exit(0) if pkgutil.find_loader('websocket') else exit(1)" >/dev/null 2>&1; then
    sudo python3 -m pip install --break-system-packages --root-user-action=ignore websocket-client==0.48.0 -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn
else
    sudo python3 -m pip install --break-system-packages --root-user-action=ignore websocket-client==0.48.0 -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn
fi

if python3 -c "import pkgutil; exit(0) if pkgutil.find_loader('requests') else exit(1)" >/dev/null 2>&1; then
    echo "requests package is installed."
else
    sudo python3 -m pip install --break-system-packages --root-user-action=ignore requests -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn
fi

if python3 -c "import pkgutil; exit(0) if pkgutil.find_loader('serial') else exit(1)" >/dev/null 2>&1; then
    echo "pyserial package is installed."
else
    sudo python3 -m pip install --break-system-packages --root-user-action=ignore pyserial -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn
fi

sudo ldconfig
sudo systemctl daemon-reload
sudo systemctl enable armcnc_service.service
sudo systemctl restart armcnc_service.service
sudo systemctl enable armcnc_python.service
sudo systemctl restart armcnc_python.service